plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.adshield.notificationmonitor'
version = '1.0.0'

android {
  namespace 'expo.modules.notificationmonitor'

  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
