"""Build the frozen four-class supplementary permission-only holdout.

This script is intentionally model-free. It reads static permission evidence,
package/label provenance, and the accepted Kali candidate audit; it never opens
a joblib/pickle model, calls predict/predict_proba, or performs training.

The four published artifacts are deterministic. Existing outputs are never
overwritten unless the newly generated bytes are identical.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pandas as pd


SCRIPT_PATH = Path(__file__).resolve()
CATEGORY_VALIDATION_DIR = SCRIPT_PATH.parent
PROJECT_ROOT = SCRIPT_PATH.parents[3]
EXPERIMENTAL_DIR = PROJECT_ROOT / "models" / "category_experimental"
FINAL_VALIDATION_DIR = PROJECT_ROOT / "models" / "category_final_validation"
KALI_DIR = CATEGORY_VALIDATION_DIR / "20260726T074051Z"
OUTPUT_DIR = CATEGORY_VALIDATION_DIR / "final_supplementary_holdout"

FEATURES_PATH = EXPERIMENTAL_DIR / "permission_features.json"
MAPPING_PATH = EXPERIMENTAL_DIR / "permission_source_mapping.json"
STATIC_PATH = PROJECT_ROOT / "data" / "datasets" / "feature_vectors_static.csv"
SYSCALL_CLASS_PATH = (
    PROJECT_ROOT / "data" / "datasets" / "feature_vectors_syscalls_frequency_5_Cat.csv"
)
BINDER_CLASS_PATH = (
    PROJECT_ROOT
    / "data"
    / "datasets"
    / "feature_vectors_syscallsbinders_frequency_5_Cat.csv"
)
HISTORICAL_SPLIT_PATH = EXPERIMENTAL_DIR / "split_manifest.csv"
NATURAL_MANIFEST_PATH = EXPERIMENTAL_DIR / "natural_split_manifest.csv"
DEVELOPMENT_MANIFEST_PATH = FINAL_VALIDATION_DIR / "artifacts" / "development_manifest.csv"
EXPLICIT_CONFLICTS_PATH = EXPERIMENTAL_DIR / "excluded_cross_label_packages.json"
BANKING_CANDIDATES_PATH = KALI_DIR / "banking_unique_candidates.csv"
SMS_CANDIDATES_PATH = KALI_DIR / "sms_unique_candidates.csv"
APK_AUDIT_PATH = KALI_DIR / "apk_audit.csv"
ELIGIBLE_APK_AUDIT_PATH = KALI_DIR / "eligible_holdout_candidates.csv"

MANIFEST_NAME = "final_holdout_manifest.csv"
FEATURES_NAME = "final_holdout_features.csv"
REPORT_NAME = "final_holdout_selection_report.json"
HASHES_NAME = "final_holdout_sha256.txt"

EXPECTED_STATIC_ROWS = 11_598
EXPECTED_STATIC_COLUMNS = 50_621
EXPECTED_FEATURE_COUNT = 153
EXPECTED_FEATURE_FILE_SHA256 = (
    "9bbbdbf826db7957a0335baefa93eb8bc3440c4edcf7f5825cccf949a105a4fd"
)
EXPECTED_ORDERED_FEATURE_SHA256 = (
    "7aecf3b202c88d707e458a3705b4e3a326a9ee062c9b1e0f209a6b9a5c087c34"
)
EXPECTED_CLASS_RUNS = {1: 1_253, 2: 2_100, 3: 3_904, 4: 2_546, 5: 1_795}
DATASET_CLASS_NAMES = {
    1: "Adware",
    2: "Banking Malware",
    3: "SMS Malware",
    4: "Riskware",
    5: "Benign",
}
CLASS_ORDER = ["Adware", "Banking Malware", "SMS Malware", "Riskware"]
CLASS_IDS = {name: class_id for class_id, name in DATASET_CLASS_NAMES.items() if class_id < 5}
MODEL_CLASS_INDEX = {name: index for index, name in enumerate(CLASS_ORDER)}
KALI_CATEGORY_NAMES = {"banking": "Banking Malware", "sms": "SMS Malware"}
HOLDOUT_PER_CLASS = 49
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")

# These immutable fingerprints were recorded by the accepted historical POC,
# final-validation run, and Kali extraction handoff.
EXPECTED_SOURCE_HASHES = {
    "data/datasets/feature_vectors_static.csv": (
        "3b229c3d570f9fb3c4d25cc3fcb912c69996574dbf058fe2da16b8a07f23c4fe"
    ),
    "data/datasets/feature_vectors_syscalls_frequency_5_Cat.csv": (
        "3415babdd76a2b77c400a9ec3a8a6057705d5a57a9e91753191ecc2946df7c00"
    ),
    "data/datasets/feature_vectors_syscallsbinders_frequency_5_Cat.csv": (
        "f345df28987fe6e3fb54cc711317dd1057a249b71ceb55f9a16cfadaee23f59d"
    ),
    "models/category_experimental/permission_features.json": (
        EXPECTED_FEATURE_FILE_SHA256
    ),
    "models/category_experimental/permission_source_mapping.json": (
        "59cfec267197b4c7efc075b47999401a9d702d245ac1a44fe0de4f7532340811"
    ),
    "models/category_experimental/split_manifest.csv": (
        "d14dd5eaece6b4772981aab800f17d919ee3dfb45abe00adb440b062ffa4cced"
    ),
    "models/category_experimental/natural_split_manifest.csv": (
        "f884942ddd45909697b4fc749dcba68b5293945652c3b524d342c87595f1c5b2"
    ),
    "models/category_experimental/excluded_cross_label_packages.json": (
        "cf57bc544bd547e2236dbc4a71c61766a75964747fbe7449175a3361299dbebd"
    ),
    "models/category_final_validation/artifacts/development_manifest.csv": (
        "3d2c69a0ff6f25865d728451c670f31184b0b6d4d3cbb13650cdae473fc8a33e"
    ),
    "models/category_final_validation/category_validation/20260726T074051Z/apk_audit.csv": (
        "d97055c6a4b41afbd1b1bcb0d6bd7ac656b0020937e150e4fc1987ff72d220cc"
    ),
    "models/category_final_validation/category_validation/20260726T074051Z/eligible_holdout_candidates.csv": (
        "4cf3d5a40064d3568812aee6e8fdeb70ab3908f5d45795854b926d53c2fc5c43"
    ),
    "models/category_final_validation/category_validation/20260726T074051Z/banking_unique_candidates.csv": (
        "d491457a1bed4d00715f3132b8ad17b945c670678397fa1cb09a735cade14c49"
    ),
    "models/category_final_validation/category_validation/20260726T074051Z/sms_unique_candidates.csv": (
        "ea0b4a5136b878744aa7055592df9fae3da49325f62c472c209a937c5b3c2160"
    ),
}


def normalize_package(value: Any) -> str:
    return str(value or "").strip().casefold()


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path, chunk_size: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(chunk_size):
            digest.update(chunk)
    return digest.hexdigest()


def project_relative(path: Path) -> str:
    return path.resolve().relative_to(PROJECT_ROOT).as_posix()


def verify_source_hashes() -> dict[str, dict[str, Any]]:
    observed: dict[str, dict[str, Any]] = {}
    for relative, expected in EXPECTED_SOURCE_HASHES.items():
        path = PROJECT_ROOT / relative
        if not path.is_file():
            raise FileNotFoundError(f"Required source is missing: {path}")
        actual = sha256_file(path)
        if actual != expected:
            raise ValueError(
                f"Source fingerprint changed for {relative}: expected {expected}, got {actual}"
            )
        observed[relative] = {"bytes": path.stat().st_size, "sha256": actual}
    return observed


def ordered_feature_hash(features: list[str]) -> str:
    payload = json.dumps(
        features, ensure_ascii=False, separators=(",", ":")
    ).encode("utf-8")
    return sha256_bytes(payload)


def load_feature_contract() -> tuple[list[str], dict[str, list[int]]]:
    features = json.loads(FEATURES_PATH.read_text(encoding="utf-8"))
    if not isinstance(features, list) or len(features) != EXPECTED_FEATURE_COUNT:
        raise ValueError("Permission feature contract must contain exactly 153 entries")
    if any(not isinstance(value, str) or not value for value in features):
        raise ValueError("Permission feature contract contains a non-string/blank value")
    if len(set(features)) != EXPECTED_FEATURE_COUNT:
        raise ValueError("Permission feature contract contains duplicate names")
    if ordered_feature_hash(features) != EXPECTED_ORDERED_FEATURE_SHA256:
        raise ValueError("Ordered permission feature contract hash changed")

    mapping = json.loads(MAPPING_PATH.read_text(encoding="utf-8"))
    mapping_features = [record["feature"] for record in mapping["features"]]
    if mapping_features != features:
        raise ValueError("Permission source mapping order differs from the 153-feature contract")
    source_by_feature: dict[str, list[int]] = {}
    for record in mapping["features"]:
        indices = [int(item["zero_based_index"]) for item in record["source_columns"]]
        if not indices:
            raise ValueError(f"Feature has no mapped source columns: {record['feature']}")
        source_by_feature[record["feature"]] = indices
    return features, source_by_feature


def parse_presence(series: pd.Series) -> tuple[np.ndarray, int]:
    text = series.fillna("").astype(str).str.strip()
    lower = text.str.casefold()
    boolean_values = lower.map({"true": 1.0, "false": 0.0})
    numeric_values = pd.to_numeric(text, errors="coerce")
    values = numeric_values.where(numeric_values.notna(), boolean_values)
    invalid = int((text.ne("") & values.isna()).sum())
    present = (values.fillna(0.0).to_numpy(dtype=np.float64) > 0.0).astype(np.uint8)
    return present, invalid


def read_static_permission_evidence(
    features: list[str], source_by_feature: dict[str, list[int]]
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    with STATIC_PATH.open(
        "r", encoding="utf-8-sig", newline="", errors="replace"
    ) as handle:
        header = next(csv.reader(handle))
    if len(header) != EXPECTED_STATIC_COLUMNS:
        raise ValueError(
            f"Static header width is {len(header)}, expected {EXPECTED_STATIC_COLUMNS}"
        )
    package_indices = [index for index, value in enumerate(header) if value == "package"]
    if package_indices != [30_246]:
        raise ValueError(f"Unexpected package column indices: {package_indices}")
    package_index = package_indices[0]

    selected_indices = sorted(
        {
            0,
            package_index,
            *(index for indices in source_by_feature.values() for index in indices),
        }
    )
    reader = pd.read_csv(
        STATIC_PATH,
        usecols=selected_indices,
        dtype=str,
        keep_default_na=False,
        low_memory=False,
        chunksize=2_048,
    )
    index_parts: list[np.ndarray] = []
    package_parts: list[np.ndarray] = []
    matrix_parts: list[np.ndarray] = []
    invalid_by_feature: Counter[str] = Counter()

    for frame in reader:
        if frame.shape[1] != len(selected_indices):
            raise ValueError("Static selected-column width changed")
        frame.columns = [f"column_{index}" for index in selected_indices]
        index_parts.append(
            pd.to_numeric(frame["column_0"], errors="raise").to_numpy(dtype=np.int64)
        )
        package_parts.append(
            frame[f"column_{package_index}"]
            .fillna("")
            .astype(str)
            .str.strip()
            .to_numpy(dtype=object)
        )
        matrix = np.zeros((len(frame), EXPECTED_FEATURE_COUNT), dtype=np.uint8)
        for feature_index, feature in enumerate(features):
            aggregate = np.zeros(len(frame), dtype=np.uint8)
            invalid = 0
            for source_index in source_by_feature[feature]:
                values, count = parse_presence(frame[f"column_{source_index}"])
                aggregate |= values
                invalid += count
            matrix[:, feature_index] = aggregate
            if invalid:
                invalid_by_feature[feature] += invalid
        matrix_parts.append(matrix)

    source_rows = np.concatenate(index_parts)
    packages = np.concatenate(package_parts)
    permission_matrix = np.vstack(matrix_parts)
    if len(source_rows) != EXPECTED_STATIC_ROWS:
        raise ValueError("Static row count changed")
    if not np.array_equal(source_rows, np.arange(EXPECTED_STATIC_ROWS, dtype=np.int64)):
        raise ValueError("Exported static row index is not exactly 0..11597")
    if invalid_by_feature:
        raise ValueError(f"Invalid mapped permission values: {dict(invalid_by_feature)}")
    if not np.isin(permission_matrix, [0, 1]).all():
        raise ValueError("Static permission matrix contains a non-binary value")
    return source_rows, packages, permission_matrix


def read_verified_labels() -> np.ndarray:
    syscall = pd.to_numeric(
        pd.read_csv(SYSCALL_CLASS_PATH, usecols=["Class"])["Class"], errors="raise"
    ).to_numpy(dtype=np.int8)
    binder = pd.to_numeric(
        pd.read_csv(BINDER_CLASS_PATH, usecols=["Class"])["Class"], errors="raise"
    ).to_numpy(dtype=np.int8)
    if len(syscall) != EXPECTED_STATIC_ROWS or len(binder) != EXPECTED_STATIC_ROWS:
        raise ValueError("Class-vector row count changed")
    if not np.array_equal(syscall, binder):
        raise ValueError("The two positional Class vectors disagree")
    expected = np.concatenate(
        [
            np.full(count, class_id, dtype=np.int8)
            for class_id, count in EXPECTED_CLASS_RUNS.items()
        ]
    )
    if not np.array_equal(syscall, expected):
        raise ValueError("Class order/runs differ from the accepted CICMalDroid alignment")
    return syscall


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def historical_package_inventory() -> tuple[set[str], dict[str, Any]]:
    split_rows = read_csv_rows(HISTORICAL_SPLIT_PATH)
    development_rows = read_csv_rows(DEVELOPMENT_MANIFEST_PATH)
    split_by_partition: dict[str, set[str]] = {}
    for split in ("train", "validation", "test"):
        split_by_partition[split] = {
            normalize_package(row["package"])
            for row in split_rows
            if row.get("split", "").strip() == split
            and normalize_package(row.get("package", ""))
        }
    split_packages = set().union(*split_by_partition.values())
    development_packages = {
        normalize_package(row.get("package", ""))
        for row in development_rows
        if normalize_package(row.get("package", ""))
    }
    forbidden = split_packages | development_packages
    return forbidden, {
        "authority": project_relative(HISTORICAL_SPLIT_PATH),
        "interpretation": (
            "split_manifest.csv is the actual balanced 4,000-row historical POC "
            "train/validation/test cohort. natural_split_manifest.csv is the full "
            "pre-downsampling source inventory and is not treated as model-exposed."
        ),
        "split_unique_packages": {
            split: len(packages) for split, packages in split_by_partition.items()
        },
        "all_split_unique_packages": len(split_packages),
        "final_development_unique_packages": len(development_packages),
        "development_packages_outside_split": len(development_packages - split_packages),
        "combined_forbidden_unique_packages": len(forbidden),
        "normalization": "package.strip().casefold()",
    }


def build_conflict_inventory(
    packages: np.ndarray, labels: np.ndarray, audit_rows: list[dict[str, str]]
) -> tuple[set[str], dict[str, set[str]], dict[str, Any]]:
    claims: dict[str, set[str]] = defaultdict(set)
    for package, label in zip(packages, labels, strict=True):
        identity = normalize_package(package)
        if identity:
            claims[identity].add(DATASET_CLASS_NAMES[int(label)])
    for row in audit_rows:
        identity = normalize_package(row.get("package", ""))
        category = row.get("category", "").strip().casefold()
        if identity and category in KALI_CATEGORY_NAMES:
            claims[identity].add(KALI_CATEGORY_NAMES[category])

    observed_cross_label = {
        identity for identity, class_claims in claims.items() if len(class_claims) > 1
    }
    explicit_payload = json.loads(EXPLICIT_CONFLICTS_PATH.read_text(encoding="utf-8"))
    explicit = {
        normalize_package(record.get("package", ""))
        for record in explicit_payload["records"]
        if normalize_package(record.get("package", ""))
    }
    conflict_inventory = explicit | observed_cross_label
    canonical = json.dumps(
        sorted(conflict_inventory), ensure_ascii=False, separators=(",", ":")
    ).encode("utf-8")
    return conflict_inventory, claims, {
        "explicit_known_conflict_packages": len(explicit),
        "observed_cross_label_packages_across_static_and_kali_sources": len(
            observed_cross_label
        ),
        "combined_unique_conflict_packages": len(conflict_inventory),
        "combined_inventory_sha256": sha256_bytes(canonical),
        "normalization": "package.strip().casefold()",
    }


def make_static_pools(
    source_rows: np.ndarray,
    packages: np.ndarray,
    labels: np.ndarray,
    matrix: np.ndarray,
    forbidden_packages: set[str],
    conflict_packages: set[str],
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, Any]]:
    pools: dict[str, list[dict[str, Any]]] = {}
    reports: dict[str, Any] = {}
    for class_name in ("Adware", "Riskware"):
        class_id = CLASS_IDS[class_name]
        positions = np.flatnonzero(labels == class_id)
        named_positions = [
            int(position)
            for position in positions
            if normalize_package(packages[int(position)])
        ]
        historical_groups = {
            normalize_package(packages[position])
            for position in named_positions
            if normalize_package(packages[position]) in forbidden_packages
        }
        conflict_groups = {
            normalize_package(packages[position])
            for position in named_positions
            if normalize_package(packages[position]) in conflict_packages
        }
        zero_positions = [
            position for position in named_positions if int(matrix[position].sum()) == 0
        ]
        eligible_positions = [
            position
            for position in named_positions
            if normalize_package(packages[position]) not in forbidden_packages
            and normalize_package(packages[position]) not in conflict_packages
            and int(matrix[position].sum()) > 0
        ]

        by_package: dict[str, list[int]] = defaultdict(list)
        for position in eligible_positions:
            by_package[normalize_package(packages[position])].append(position)
        records: list[dict[str, Any]] = []
        for identity, group_positions in by_package.items():
            representative = min(group_positions, key=lambda value: int(source_rows[value]))
            vector = matrix[representative].astype(np.uint8, copy=True)
            records.append(
                {
                    "class_name": class_name,
                    "dataset_class_id": class_id,
                    "model_class_index": MODEL_CLASS_INDEX[class_name],
                    "package": str(packages[representative]).strip(),
                    "normalized_package": identity,
                    "sha256": "",
                    "sha256_available": False,
                    "source_type": "cicmaldroid_static_matrix",
                    "source_artifact": project_relative(STATIC_PATH),
                    "source_row_index": int(source_rows[representative]),
                    "source_path": "",
                    "positive_feature_count": int(vector.sum()),
                    "features": vector,
                }
            )
        records.sort(
            key=lambda row: (
                row["normalized_package"],
                row["sha256"],
                int(row["source_row_index"]),
            )
        )
        pools[class_name] = records
        reports[class_name] = {
            "source_rows_for_class": int(len(positions)),
            "named_source_rows": len(named_positions),
            "historical_or_development_overlap_groups": len(historical_groups),
            "known_conflict_groups": len(conflict_groups),
            "known_conflict_packages": sorted(conflict_groups),
            "all_zero_source_rows": len(zero_positions),
            "eligible_rows_before_package_deduplication": len(eligible_positions),
            "final_eligible_unique_packages": len(records),
            "rows_removed_by_package_deduplication": len(eligible_positions) - len(records),
            "sha256_evidence_available": False,
            "representative_rule": "minimum source_row_index per normalized package",
        }
    return pools, reports


def parse_binary_vector(row: dict[str, str], features: list[str]) -> np.ndarray:
    values: list[int] = []
    for feature in features:
        value = row.get(feature, "")
        if value not in {"0", "1"}:
            raise ValueError(f"Non-binary APK candidate feature {feature}={value!r}")
        values.append(int(value))
    return np.asarray(values, dtype=np.uint8)


def make_apk_pools(
    features: list[str],
    audit_rows: list[dict[str, str]],
    forbidden_packages: set[str],
    conflict_packages: set[str],
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, Any]]:
    audit_hash_counts = Counter(
        row.get("sha256", "").strip().casefold()
        for row in audit_rows
        if row.get("sha256", "").strip()
    )
    source_paths = {
        "Banking Malware": BANKING_CANDIDATES_PATH,
        "SMS Malware": SMS_CANDIDATES_PATH,
    }
    pools: dict[str, list[dict[str, Any]]] = {}
    reports: dict[str, Any] = {}

    for class_name, source_path in source_paths.items():
        rows = read_csv_rows(source_path)
        if not rows:
            raise ValueError(f"Candidate source is empty: {source_path}")
        fieldnames = list(rows[0].keys())
        if fieldnames[-EXPECTED_FEATURE_COUNT:] != features:
            raise ValueError(f"APK candidate feature order changed: {source_path}")

        source_identities = [normalize_package(row.get("package", "")) for row in rows]
        if any(not identity for identity in source_identities):
            raise ValueError(f"Blank package in unique candidate source: {source_path}")
        if len(source_identities) != len(set(source_identities)):
            raise ValueError(f"Duplicate normalized package in candidate source: {source_path}")

        historical_groups: set[str] = set()
        known_conflict_groups: set[str] = set()
        zero_groups: set[str] = set()
        invalid_hash_groups: set[str] = set()
        records: list[dict[str, Any]] = []
        for row in rows:
            identity = normalize_package(row["package"])
            vector = parse_binary_vector(row, features)
            sha256 = row.get("sha256", "").strip().casefold()
            if identity in forbidden_packages:
                historical_groups.add(identity)
                continue
            if identity in conflict_packages:
                known_conflict_groups.add(identity)
                continue
            if int(vector.sum()) == 0:
                zero_groups.add(identity)
                continue
            if SHA256_PATTERN.fullmatch(sha256) is None or audit_hash_counts[sha256] != 1:
                invalid_hash_groups.add(identity)
                continue
            expected_count = int(row["matched_schema_permission_count"])
            if int(vector.sum()) != expected_count:
                raise ValueError(f"Feature-count mismatch for APK candidate {identity}")
            records.append(
                {
                    "class_name": class_name,
                    "dataset_class_id": CLASS_IDS[class_name],
                    "model_class_index": MODEL_CLASS_INDEX[class_name],
                    "package": str(row["package"]).strip(),
                    "normalized_package": identity,
                    "sha256": sha256,
                    "sha256_available": True,
                    "source_type": "kali_static_apk_manifest_audit",
                    "source_artifact": project_relative(source_path),
                    "source_row_index": "",
                    "source_path": row.get("source_path", "").strip(),
                    "positive_feature_count": int(vector.sum()),
                    "features": vector,
                }
            )

        # Reapply the one-representative rule defensively even though the input
        # source is already package-unique.
        by_package: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for record in records:
            by_package[record["normalized_package"]].append(record)
        unique_records: list[dict[str, Any]] = []
        for identity, group in by_package.items():
            representative = min(
                group,
                key=lambda row: (row["sha256"], row["source_path"]),
            )
            unique_records.append(representative)
        unique_records.sort(
            key=lambda row: (
                row["normalized_package"],
                row["sha256"],
                row["source_path"],
            )
        )
        hashes = [record["sha256"] for record in unique_records]
        if len(hashes) != len(set(hashes)):
            raise ValueError(f"Duplicate SHA-256 remains in {class_name} candidate pool")
        pools[class_name] = unique_records
        reports[class_name] = {
            "source_unique_candidate_rows": len(rows),
            "historical_or_development_overlap_groups": len(historical_groups),
            "known_conflict_groups": len(known_conflict_groups),
            "known_conflict_packages": sorted(known_conflict_groups),
            "all_zero_groups": len(zero_groups),
            "all_zero_packages": sorted(zero_groups),
            "invalid_or_nonunique_sha256_groups": len(invalid_hash_groups),
            "final_eligible_unique_packages": len(unique_records),
            "sha256_evidence_available": True,
            "unique_available_sha256": len(set(hashes)),
            "representative_rule": (
                "minimum lowercase SHA-256, then source_path per normalized package"
            ),
        }
    all_hashes = [
        record["sha256"]
        for class_name in ("Banking Malware", "SMS Malware")
        for record in pools[class_name]
    ]
    if len(all_hashes) != len(set(all_hashes)):
        raise ValueError("Banking/SMS eligible pools share a SHA-256")
    return pools, reports


def csv_bytes(fieldnames: list[str], rows: Iterable[dict[str, Any]]) -> bytes:
    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(
        buffer, fieldnames=fieldnames, extrasaction="raise", lineterminator="\n"
    )
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


def publish_frozen(files: dict[str, bytes]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, payload in files.items():
        target = OUTPUT_DIR / name
        if target.exists() and target.read_bytes() != payload:
            raise FileExistsError(
                f"Refusing to overwrite frozen artifact with different bytes: {target}"
            )
    for name, payload in files.items():
        target = OUTPUT_DIR / name
        if target.exists():
            continue
        temporary = target.with_name(f".{target.name}.tmp")
        try:
            temporary.write_bytes(payload)
            os.replace(temporary, target)
        finally:
            temporary.unlink(missing_ok=True)


def verify_published_outputs(features: list[str], expected_hashes: dict[str, str]) -> None:
    for name, expected in expected_hashes.items():
        actual = sha256_file(OUTPUT_DIR / name)
        if actual != expected:
            raise AssertionError(f"Published hash mismatch for {name}")
    manifest_rows = read_csv_rows(OUTPUT_DIR / MANIFEST_NAME)
    feature_rows = read_csv_rows(OUTPUT_DIR / FEATURES_NAME)
    if len(manifest_rows) != 196 or len(feature_rows) != 196:
        raise AssertionError("Published holdout must contain exactly 196 aligned rows")
    if list(feature_rows[0].keys()) != features:
        raise AssertionError("Published feature columns differ from the exact contract")
    if any(value not in {"0", "1"} for row in feature_rows for value in row.values()):
        raise AssertionError("Published feature file contains a non-binary value")
    if any(sum(int(value) for value in row.values()) == 0 for row in feature_rows):
        raise AssertionError("Published feature file contains an all-zero vector")
    packages = [row["normalized_package"] for row in manifest_rows]
    if len(packages) != len(set(packages)):
        raise AssertionError("Published manifest contains duplicate normalized packages")
    counts = Counter(row["class_name"] for row in manifest_rows)
    if counts != Counter({name: HOLDOUT_PER_CLASS for name in CLASS_ORDER}):
        raise AssertionError(f"Published class counts changed: {dict(counts)}")
    hashes = [row["sha256"] for row in manifest_rows if row["sha256"]]
    if len(hashes) != 98 or len(hashes) != len(set(hashes)):
        raise AssertionError("Published available SHA-256 values must be 98/98 unique")


def main() -> int:
    print("Verifying immutable source fingerprints...", flush=True)
    source_fingerprints = verify_source_hashes()
    features, source_by_feature = load_feature_contract()
    print("Reading the 153 mapped static permission features (no model access)...", flush=True)
    source_rows, static_packages, static_matrix = read_static_permission_evidence(
        features, source_by_feature
    )
    labels = read_verified_labels()

    natural_rows = read_csv_rows(NATURAL_MANIFEST_PATH)
    if len(natural_rows) != 9_543:
        raise ValueError("Natural source-inventory row count changed")
    # Verify the source inventory remains positionally consistent without using
    # its bookkeeping split labels as evidence of model exposure.
    for row in natural_rows:
        position = int(row["source_row_index"])
        if normalize_package(row["package"]) != normalize_package(static_packages[position]):
            raise ValueError(f"Natural manifest package mismatch at source row {position}")
        if row["class_name"] != DATASET_CLASS_NAMES[int(labels[position])]:
            raise ValueError(f"Natural manifest class mismatch at source row {position}")

    audit_rows = read_csv_rows(APK_AUDIT_PATH)
    if len(audit_rows) != 7_201:
        raise ValueError("Accepted APK audit row count changed")
    forbidden_packages, historical_report = historical_package_inventory()
    conflict_packages, conflict_claims, conflict_report = build_conflict_inventory(
        static_packages, labels, audit_rows
    )

    static_pools, static_reports = make_static_pools(
        source_rows,
        static_packages,
        labels,
        static_matrix,
        forbidden_packages,
        conflict_packages,
    )
    apk_pools, apk_reports = make_apk_pools(
        features, audit_rows, forbidden_packages, conflict_packages
    )
    pools = {**static_pools, **apk_pools}
    candidate_reports = {**static_reports, **apk_reports}

    expected_counts = {
        "Adware": 138,
        "Banking Malware": 147,
        "SMS Malware": 49,
        "Riskware": 1_005,
    }
    actual_counts = {name: len(pools[name]) for name in CLASS_ORDER}
    if actual_counts != expected_counts:
        raise AssertionError(
            f"Final eligible candidate inventory changed: {actual_counts}; "
            f"expected {expected_counts}"
        )
    if any(count < HOLDOUT_PER_CLASS for count in actual_counts.values()):
        raise AssertionError("At least one class has fewer than 49 eligible packages")

    # No normalized package may survive in more than one category.
    package_to_classes: dict[str, set[str]] = defaultdict(set)
    for class_name, records in pools.items():
        for record in records:
            package_to_classes[record["normalized_package"]].add(class_name)
    surviving_cross_category = {
        package: names for package, names in package_to_classes.items() if len(names) > 1
    }
    if surviving_cross_category:
        raise AssertionError(
            f"Cross-category package conflicts survived: {surviving_cross_category}"
        )

    selected: list[dict[str, Any]] = []
    for class_name in CLASS_ORDER:
        # Pools are already sorted by normalized package, lowercase SHA-256,
        # and their source-specific deterministic tie-breaker.
        selected.extend(pools[class_name][:HOLDOUT_PER_CLASS])
    if len(selected) != 196:
        raise AssertionError("Deterministic selection did not produce exactly 196 samples")

    selected_packages = [record["normalized_package"] for record in selected]
    if len(set(selected_packages)) != 196:
        raise AssertionError("Selected normalized packages are not globally unique")
    if set(selected_packages) & forbidden_packages:
        raise AssertionError("A historical/development package entered the selection")
    if set(selected_packages) & conflict_packages:
        raise AssertionError("A known label-conflict package entered the selection")
    if any(int(record["features"].sum()) == 0 for record in selected):
        raise AssertionError("An all-zero permission vector entered the selection")

    selected_hashes = [record["sha256"] for record in selected if record["sha256"]]
    if len(selected_hashes) != 98 or len(set(selected_hashes)) != 98:
        raise AssertionError("Expected 98 available and unique Banking/SMS hashes")

    manifest_fieldnames = [
        "holdout_row_index",
        "class_name",
        "dataset_class_id",
        "model_class_index",
        "package",
        "normalized_package",
        "sha256",
        "sha256_available",
        "source_type",
        "source_artifact",
        "source_row_index",
        "source_path",
        "positive_feature_count",
        "ordered_feature_contract_sha256",
    ]
    manifest_rows: list[dict[str, Any]] = []
    feature_rows: list[dict[str, int]] = []
    for row_index, record in enumerate(selected):
        manifest_rows.append(
            {
                "holdout_row_index": row_index,
                "class_name": record["class_name"],
                "dataset_class_id": record["dataset_class_id"],
                "model_class_index": record["model_class_index"],
                "package": record["package"],
                "normalized_package": record["normalized_package"],
                "sha256": record["sha256"],
                "sha256_available": str(record["sha256_available"]).lower(),
                "source_type": record["source_type"],
                "source_artifact": record["source_artifact"],
                "source_row_index": record["source_row_index"],
                "source_path": record["source_path"],
                "positive_feature_count": record["positive_feature_count"],
                "ordered_feature_contract_sha256": EXPECTED_ORDERED_FEATURE_SHA256,
            }
        )
        feature_rows.append(
            {
                feature: int(value)
                for feature, value in zip(features, record["features"], strict=True)
            }
        )

    manifest_payload = csv_bytes(manifest_fieldnames, manifest_rows)
    features_payload = csv_bytes(features, feature_rows)
    manifest_sha = sha256_bytes(manifest_payload)
    features_sha = sha256_bytes(features_payload)

    candidate_pool_report = {
        class_name: {
            **candidate_reports[class_name],
            "minimum_required": HOLDOUT_PER_CLASS,
            "minimum_satisfied": len(pools[class_name]) >= HOLDOUT_PER_CLASS,
            "selected": HOLDOUT_PER_CLASS,
        }
        for class_name in CLASS_ORDER
    }
    selected_conflict_claims = {
        package: sorted(conflict_claims.get(package, set()))
        for package in sorted(conflict_packages)
        if any(
            package in set(candidate_reports[name].get("known_conflict_packages", []))
            for name in CLASS_ORDER
        )
    }
    report = {
        "status": "frozen_unevaluated",
        "purpose": "final supplementary package-disjoint four-class holdout",
        "protocol": {
            "package_normalization": "package.strip().casefold()",
            "historical_exclusion": (
                "all packages in actual historical train/validation/test and the final "
                "development cohort"
            ),
            "known_conflicts_excluded_from_every_claimed_category": True,
            "one_representative_per_normalized_package": True,
            "sha256_unique_where_evidence_available": True,
            "permission_feature_count": EXPECTED_FEATURE_COUNT,
            "features_binary": True,
            "minimum_positive_permission_features": 1,
            "selection_rule": (
                "Within each class, filter all eligibility rules; select one representative "
                "per normalized package; sort by normalized_package, lowercase SHA-256 "
                "(blank when unavailable), then source_row_index/source_path; take first 49."
            ),
            "class_output_order": CLASS_ORDER,
            "natural_manifest_interpretation": historical_report["interpretation"],
        },
        "feature_contract": {
            "count": EXPECTED_FEATURE_COUNT,
            "source": project_relative(FEATURES_PATH),
            "source_json_file_sha256": EXPECTED_FEATURE_FILE_SHA256,
            "ordered_compact_json_sha256": EXPECTED_ORDERED_FEATURE_SHA256,
            "final_feature_csv_has_exactly_153_columns": True,
            "final_feature_order_matches_contract": True,
        },
        "label_provenance": {
            "Adware/Riskware": (
                "CICMalDroid static rows use the accepted positional alignment to two "
                "identical accompanying Class vectors; no per-row APK hash join exists."
            ),
            "Banking Malware/SMS Malware": (
                "Labels are inherited from the accepted, audited Kali category source roots."
            ),
            "dynamic_syscall_or_binder_features_used": False,
            "class_columns_only_from_accompanying_dynamic_files": True,
        },
        "historical_package_inventory": historical_report,
        "conflict_inventory": {
            **conflict_report,
            "candidate_pool_conflict_claims": selected_conflict_claims,
        },
        "candidate_pools_before_holdout_selection": candidate_pool_report,
        "final_eligible_unique_package_counts": actual_counts,
        "selection": {
            "samples_per_class": HOLDOUT_PER_CLASS,
            "total_samples": len(selected),
            "class_counts": dict(Counter(record["class_name"] for record in selected)),
            "unique_normalized_packages": len(set(selected_packages)),
            "sha256_evidence_samples": len(selected_hashes),
            "unique_available_sha256": len(set(selected_hashes)),
            "sha256_coverage_by_class": {
                class_name: sum(
                    bool(record["sha256"])
                    for record in selected
                    if record["class_name"] == class_name
                )
                for class_name in CLASS_ORDER
            },
        },
        "verification": {
            "total_samples_is_196": len(selected) == 196,
            "each_category_has_49": all(
                sum(record["class_name"] == class_name for record in selected) == 49
                for class_name in CLASS_ORDER
            ),
            "normalized_packages_are_196_of_196_unique": len(set(selected_packages)) == 196,
            "no_historical_or_development_package_overlap": not bool(
                set(selected_packages) & forbidden_packages
            ),
            "no_known_label_conflicts": not bool(set(selected_packages) & conflict_packages),
            "no_cross_category_package_conflicts": not bool(surviving_cross_category),
            "available_sha256_values_are_98_of_98_unique": (
                len(selected_hashes) == len(set(selected_hashes)) == 98
            ),
            "exact_153_feature_order_and_hash": True,
            "all_features_binary": all(
                np.isin(record["features"], [0, 1]).all() for record in selected
            ),
            "no_all_zero_feature_vectors": all(
                int(record["features"].sum()) >= 1 for record in selected
            ),
            "manifest_and_feature_rows_positionally_aligned": True,
        },
        "safety": {
            "category_model_loaded": False,
            "predictions_generated": False,
            "probabilities_generated": False,
            "training_performed": False,
            "retraining_performed": False,
            "fastapi_modified": False,
        },
        "source_fingerprints": source_fingerprints,
        "outputs": {
            MANIFEST_NAME: {"bytes": len(manifest_payload), "sha256": manifest_sha},
            FEATURES_NAME: {"bytes": len(features_payload), "sha256": features_sha},
            "hash_manifest_note": (
                "final_holdout_sha256.txt hashes manifest, features, and report; it does "
                "not self-hash."
            ),
        },
    }
    report_payload = (
        json.dumps(report, indent=2, ensure_ascii=False, sort_keys=False) + "\n"
    ).encode("utf-8")
    report_sha = sha256_bytes(report_payload)
    hashes_payload = (
        f"{manifest_sha}  {MANIFEST_NAME}\n"
        f"{features_sha}  {FEATURES_NAME}\n"
        f"{report_sha}  {REPORT_NAME}\n"
    ).encode("utf-8")

    payloads = {
        MANIFEST_NAME: manifest_payload,
        FEATURES_NAME: features_payload,
        REPORT_NAME: report_payload,
        HASHES_NAME: hashes_payload,
    }
    publish_frozen(payloads)
    verify_published_outputs(
        features,
        {
            MANIFEST_NAME: manifest_sha,
            FEATURES_NAME: features_sha,
            REPORT_NAME: report_sha,
            HASHES_NAME: sha256_bytes(hashes_payload),
        },
    )

    print("Final eligible unique-package counts:", flush=True)
    for class_name in CLASS_ORDER:
        print(f"  {class_name}: {actual_counts[class_name]}", flush=True)
    print(f"Frozen holdout: {OUTPUT_DIR}", flush=True)
    print("No category model was loaded; no predictions or training were performed.", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
